# Site Settings
baseurl: "muuky.github.io"
url : ""

# Blog Settings
theme_settings :
  title : Grape Theme
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/profile.png
    username : Muuky
    description : 취미 python 개발자, 취미 서버 운용
    experience :
      - start : 2016-12
        end : 2020-02
        experience : M.S.Student
      - start : 2014-03
        end : 2018-02
        experience : B.S. Degree Student
      - start : 2012-02
        end : 2014-02
        experience : A.S. Student 
    skills : 
      - skill : Python
        value : 75  # Percent value
      - skill : AI
        value : 20
      - skill : git
        value : 20
        
  # Icons
  icons :
    email: muuuky0@gmail.com # Full email address, e.g. "sample@google.com"
    linkedin:  # Full URL 
    github: 
    gitlab: 
    bitbucket: 
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname :

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
